# Generated by Django 6.0 on 2025-12-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo de profil'),
        ),
    ]
