# Generated by Django 6.0 on 2025-12-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('delegate', 'Déléguée'), ('member', 'Membre')], default='member', max_length=10),
        ),
    ]
