# Generated by Django 6.0 on 2025-12-17 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='members',
        ),
        migrations.AddField(
            model_name='commission',
            name='min_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacité min'),
        ),
        migrations.AddField(
            model_name='commission',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_commissions', to='member.member', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Laisser vide pour illimité', null=True, verbose_name='Capacité max'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigné le')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='event.commission', verbose_name='Commission')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='member.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
                'unique_together': {('commission', 'member')},
            },
        ),
    ]
